name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: '${{ secrets.DEPLOY_KEY }}'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Server
        env:
          REMOTE_DIR: /var/www/luhas.gratis/
        run: |
          # Remove all existing files in the remote directory
          ssh -o StrictHostKeyChecking=no servore@80.108.204.51 "rm -rf $REMOTE_DIR/*"
          
          # Copy the built files to the server
          scp -o StrictHostKeyChecking=no -r dist/* servore@80.108.204.51:$REMOTE_DIR
      
          # Restart Nginx to apply changes
          ssh -o StrictHostKeyChecking=no servore@80.108.204.51 "sudo -n systemctl reload nginx"
      