name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest        # <-- back to a supported image
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - run: npm ci && npm run build    # combined install + build

      - name: Deploy to Server
        env:
          HOST: 80.108.204.51
          USER: servore
          REMOTE_DIR: /var/www/luhas.gratis
        run: |
          rsync -az --delete dist/ "$USER@$HOST:$REMOTE_DIR"
          ssh -o StrictHostKeyChecking=no "$USER@$HOST" \
              'sudo -n systemctl reload nginx'
