name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: 80.108.204.51
      USER: servore
      REMOTE_DIR: /var/www/luhas.gratis

    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - run: npm ci && npm run build

      - name: Deploy to server
        run: |
          rsync -az --delete dist/ "$USER@$HOST:$REMOTE_DIR"
          ssh "$USER@$HOST" 'sudo -n systemctl reload nginx'